name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Giai nen file code
      run: unzip VLESSRealityDemo.zip

    - name: Fix Repositories va ha version SDK
      run: |
        cd VLESSRealityDemo
        cat <<EOF > new_settings.gradle
        pluginManagement {
            repositories {
                google()
                mavenCentral()
                gradlePluginPortal()
            }
        }
        dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
            repositories {
                google()
                mavenCentral()
            }
        }
        EOF
        cat settings.gradle >> new_settings.gradle
        mv new_settings.gradle settings.gradle
        
        sed -i 's/compileSdk 35/compileSdk 34/g' app/build.gradle
        sed -i 's/targetSdk 35/targetSdk 34/g' app/build.gradle

    - name: Tao Gradle Wrapper v8.7 va Tien hanh Build APK
      run: |
        cd VLESSRealityDemo
        gradle wrapper --gradle-version 8.7
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Xuat file APK
      uses: actions/upload-artifact@v4
      with:
        name: Ung-dung-cua-ban
        path: VLESSRealityDemo/app/build/outputs/apk/debug/app-debug.apk
